# Generated by Django 5.2 on 2025-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(blank=True, max_length=40)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('guardian_name', models.CharField(blank=True, max_length=40)),
                ('guardian_occupation', models.CharField(blank=True, max_length=40)),
                ('guardians_mobile', models.CharField(blank=True, max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('training_mode', models.CharField(max_length=20)),
                ('training_location', models.CharField(max_length=50)),
                ('preferred_timings', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
