# Generated by Django 5.1.7 on 2025-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Python Full Stack', 'Python Full Stack'), ('Java Full Stack', 'Java Full Stack'), ('MERN Stack', 'MERN Stack')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_location',
            field=models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Cochin', 'Cochin'), ('Calicut', 'Calicut')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
