# Generated by Django 5.1.7 on 2025-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_course_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_timings',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_mode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
