# Generated by Django 5.1.7 on 2025-05-27 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_address_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('PHP Full Stack', 'PHP Full Stack'), ('PYTHON Full Stack', 'PYTHON Full Stack'), ('JAVA Full Stack', 'JAVA Full Stack'), ('C#.NET Core 7 Full Stack', 'C#.NET Core 7 Full Stack'), ('MEAN Full Stack', 'MEAN Full Stack'), ('MERN Full Stack', 'MERN Full Stack'), ('Data Science & AI (Python Guru)', 'Data Science & AI (Python Guru)'), ('Python Mastery (Python/Django/MySQL)', 'Python Mastery (Python/Django/MySQL)'), ('Google Flutter Mobile App Development (iOS/Android)', 'Google Flutter Mobile App Development (iOS/Android)'), ('UI/UX Designing', 'UI/UX Designing'), ('Digital Marketing Master Program', 'Digital Marketing Master Program'), ('Software Testing Advanced (Manual/Automation)', 'Software Testing Advanced (Manual/Automation)'), ('Software Testing Manual (ISTQB)', 'Software Testing Manual (ISTQB)'), ('Selenium TestNG & Cucumber/Appium Mobile/QTP/Loadrunner/Jmeter/Jira', 'Selenium TestNG & Cucumber/Appium Mobile/QTP/Loadrunner/Jmeter/Jira'), ('Computer Networking (CCNA)', 'Computer Networking (CCNA)'), ('Server Admin (MCSE)', 'Server Admin (MCSE)'), ('Server Admin (RHCE)', 'Server Admin (RHCE)'), ('Networking & Server Admin (CCNA/MCSE/Hardware)', 'Networking & Server Admin (CCNA/MCSE/Hardware)'), ('Networking & Server Admin (CCNA/RHCE/Hardware)', 'Networking & Server Admin (CCNA/RHCE/Hardware)'), ('Networking & Server Admin (CCNA/MCSE/RHCE/Hardware)', 'Networking & Server Admin (CCNA/MCSE/RHCE/Hardware)'), ('Security Surveillance & Networking Internship (CCNA/CCTV/Hardware)', 'Security Surveillance & Networking Internship (CCNA/CCTV/Hardware)'), ('Cloud Admin (AWS/MS AZURE)', 'Cloud Admin (AWS/MS AZURE)'), ('Cloud & Networking Admin (CCNA/AWS/Hardware)', 'Cloud & Networking Admin (CCNA/AWS/Hardware)'), ('Cloud & Networking Admin (CCNA/MS Azure/Hardware)', 'Cloud & Networking Admin (CCNA/MS Azure/Hardware)'), ('Cloud & Networking Admin (CCNA/AWS)', 'Cloud & Networking Admin (CCNA/AWS)'), ('Cloud & Networking Admin (CCNA/MS Azure)', 'Cloud & Networking Admin (CCNA/MS Azure)'), ('Cloud & Server Admin (MCSE/AWS/Hardware)', 'Cloud & Server Admin (MCSE/AWS/Hardware)'), ('Cloud & Server Admin (MCSE/MS Azure/Hardware)', 'Cloud & Server Admin (MCSE/MS Azure/Hardware)'), ('Cloud & Server Admin (RHCE/AWS/Hardware)', 'Cloud & Server Admin (RHCE/AWS/Hardware)'), ('Cloud & Server Admin (RHCE/MS Azure/Hardware)', 'Cloud & Server Admin (RHCE/MS Azure/Hardware)'), ('Cloud, Networking, & Server Admin (CCNA/AWS/AZURE/MCSE/RHCE/Hardware)', 'Cloud, Networking, & Server Admin (CCNA/AWS/AZURE/MCSE/RHCE/Hardware)'), ('DevOps Mastery (All together)', 'DevOps Mastery (All together)'), ('DevOps - Selective', 'DevOps - Selective'), ('Academic Project', 'Academic Project'), ('MS Office (Word/Excel/Power Point/Outlook)', 'MS Office (Word/Excel/Power Point/Outlook)'), ('Data Analytics', 'Data Analytics'), ('Advanced MS Excel', 'Advanced MS Excel'), ('Graphic Designing (Photoshop)', 'Graphic Designing (Photoshop)'), ('Graphic Designing (Photoshop/Illustrator)', 'Graphic Designing (Photoshop/Illustrator)'), ('None of the above, will discuss directly', 'None of the above, will discuss directly')], max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_timings',
            field=models.CharField(choices=[('Between 8am - 10am', 'Between 8am - 10am'), ('Between 9am - 1pm', 'Between 9am - 1pm'), ('Between 1pm - 6pm', 'Between 1pm - 6pm'), ('Between 6pm - 10pm', 'Between 6pm - 10pm')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_location',
            field=models.CharField(choices=[('Technopark TVM', 'Technopark TVM'), ('Thampanoor TVM', 'Thampanoor TVM'), ('Kochi', 'Kochi'), ('Nagercoil', 'Nagercoil'), ('Online', 'Online')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
